seed: 0
batch_size: 256
T: 4
encoding: direct
model: spiking_resnet18
dataset: CIFAR100
data_path: ~/datasets/CIFAR100
workers: 16
attack: FGSM
attack_eps: 2
resume: ./checkpoints/ResNet18_CIFAR100.pth
output_dir: ./logs/cifar100
